config/routes.rb
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

Rails.application.routes.draw do
  resources :comments
  root to: 'static_pages#home'
  get '/welcome(/:name)', to: 'static_pages#home'

  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  resources :gossips
  

end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :affiliations, dependent: :delete_all
  has_many :tags, through: :affiliations
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :affiliations
  has_many :gossips, through: :affiliations
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new

    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @gossip = Gossip.all

    @comment = Comment.new(gossip_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:author, :comment)
    end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index

  end

  def show

      @gossip = Gossip.find(params[:id])

    @id = params[:id]
  end

  def new
    @gossip = Gossip.new
  end


  def create
    @mygossip = gossip_params
    @gossip = Gossip.new(title: @mygossip[:title] , content: @mygossip[:content] , user_id: @mygossip[:user_id])
    if @gossip.save
      redirect_to root_path
    end

end



def edit

@gossip = Gossip.find(params[:id])
end

def update
  @gossip = Gossip.find(params[:id])
  if @gossip.update(gossip_params)

    redirect_to root_path
  else
    render :edit
  end
end

def destroy

    @gossip = Gossip.find(params[:id])
    @gossip.destroy
  redirect_to root_path
end



  private
  def gossip_params
    params.require(:gossip).permit(:title, :content, :user_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = User.all
    @gossip = Gossip.all
    @name = params[:name]
  end
  def team
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Author:</strong>
    <%= comment.author %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.comment %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_area :comment %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/gossips/create.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form action= <%= gossips_path %> method="POST">
          <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
          <input type="text" name="gossip_text">

          <input type="submit" value="Valider">
    </form>


  </body>
</html>

app/views/gossips/edit.html.erb
  <h1>PAGE POTIN !</h1>

      <p>
        <h2> Voici le potin n° <%= @gossip.id %></h2>
        <b><h3> TITRE :</h3></b><%= @gossip.title %> <br/>
        <b><h3> Le contenu du potin :</h3></b> <%= @gossip.content %> <br/></br>






<%= form_for @gossip do |f| %>
    <div class="form-group">
        <label>Titre de l'article</label>
        <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
        <label>Contenu de l'article</label>
        <%= f.text_area :content, class: 'form-control' %>
        <%= f.hidden_field :user_id, :value => 11 %>
    </div>
    <div class="form-group">
        <%= f.submit "Proceed", class: "btn btn-primary"%>
    </div>
<% end %>

app/views/gossips/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    Yo yo page index 

  </body>
</html>

app/views/gossips/new.html.erb
<h1>Créer un article</h1>

<%= form_for @gossip do |f| %>
    <div class="form-group">
        <label>Titre de l'article</label>
        <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
        <label>Contenu de l'article</label>
        <%= f.text_area :content, class: 'form-control' %>
        <%= f.hidden_field :user_id, :value => 11 %>
    </div>
    <div class="form-group">
        <%= f.submit "Proceed", class: "btn btn-primary"%>
    </div>
<% end %>

app/views/gossips/show.html.erb
    <h1>PAGE POTIN !</h1>



<div class="card text-center">
  <div class="card-header">
    Featured
  </div>
  <div class="card-body">
    <h5 class="card-title">potin n° <%= @id %></h5>
    <p class="card-text"><%= @gossip.content %></p>
    
    <%= button_to 'Delete gossip', @gossip, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
  <div class="card-footer text-muted">
    2 days ago
  </div>
</div>


<h1>Commentaires</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">G0SSIPY</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">Potins</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/team">Team</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/contact">contact</a>
          </li>
        </ul>

      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>Bienvenue sur la page CONTACT</h1>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

        <h1>G0ssipy</h1>
        <p>Bienvenue sur mon site de Gossips
        <%= @name %>

        </p>

        <p><h3>Voici la liste de tous les potins, tu peux aussi en créer un en cliquant <a href="/gossips/new">ici</a>.</h3>
     ________________________________________</p>
     <% @gossip.each_with_index do |gossip,index| %>
       <p>
         <%= @gossip[index].title %> -
         <%= @gossip[index].user.first_name %><br/>
         <%= @gossip[index].created_at %>

         <a href="gossips/<%=gossip.id%>">lien Gossip</a>
         ________________________________________
       </p>
     <% end %>







  </body>
</html>

app/views/static_pages/team.html.erb
<h1>Bienvenue sur la page TEAM</h1>